config/routes.rb
Mccm::Application.routes.draw do
	get "users/new"

	resources :news, only: [:new, :edit, :update, :delete, :show]
	resources :videos, only: [:index, :show,:update, :delete]
	resources :sessions, only: [:new, :create, :destroy]
	resources :settings, only: [:update, :edit]

	resources :carousel_images, only: [:new, :update, :delete, :show]

	resources :users do
		member do
			get :email
			get :files
		end
	end

	resources :news do
		member do
			patch :edit
		end
	end

	match '/presentations',		to: 'static_pages#presentations',	 via: 'get'
	match '/datasheets',		      to: 'static_pages#datasheets',	       via: 'get'	
	match '/results',		      to: 'static_pages#results',	       via: 'get'
	match '/help', 		        to: 'static_pages#help', 	         via: 'get'
	match '/about', 		      to: 'static_pages#about', 	       via: 'get'
	match '/home', 		        to: 'static_pages#home', 	         via: 'get'
	match '/register', 	      to: 'users#new', 			             via: 'get'
	match '/signin',          to: 'sessions#new',                via: 'get'
	match '/signout',         to: 'sessions#destroy',            via: 'delete'
	match '/verify', 		to: 'static_pages#verifyaccount', via: 'get'
	match '/invited', to: 'static_pages#inviteaccount', via: 'get'
	match 'admin_subpages/staticpages', to: 'admins#staticpages', via: 'get'
	match '/admin_subpages/staticpages/home', to: 'adminsstaticpages#home', via: 'get'
	match '/admin_subpages/staticpages/about', to: 'adminsstaticpages#about', via: 'get'
	match '/admin_subpages/staticpages/datasheets', to: 'adminsstaticpages#datasheets', via: 'get'
	match '/admin_subpages/staticpages/presentations_papers', to: 'adminsstaticpages#presentations_papers', via: 'get'
	match '/admin_subpages/staticpages/videos', to: 'adminsstaticpages#videos', via: 'get'
	patch '/admin_subpages/staticpages/home' => "adminsstaticpages#updatehome", :as => "admin_updatehome"

	match '/admin_subpages/', to: 'admins#index',   via: 'get'
	match '/admin_subpages/index', to: 'admins#index', via: 'get'
	match '/admin_subpages/news', to: 'admins#news', via: 'get'
	match '/admin_subpages/settings', to: 'admins#settings', via: 'get'
	match '/admin_subpages/videos', to: 'admins#videos', via: 'get'
	match '/admin_subpages/results', to: 'admins#results', via: 'get'
	match '/admin_subpages/presentations', to: 'admins#presentations', via: 'get'
	match '/admin_subpages/help', to: 'admins#help', via: 'get'
	match '/admin_subpages/about', to: 'admins#about', via: 'get'
	match '/admin_subpages/users', to: 'admins#users', via: 'get'
	match '/admin_subpages/placeholder', to: 'admins#placeholder', via: 'get'
	match '/admin_subpages/carouselimages', to: 'admins#carouselimages', via: 'get'
	match '/admin_subpages/inviteusers', to: 'admins#inviteusers', via: 'get'

	match '/admin_subpages/createnews', to: 'admins#createnews', via: 'get'
	match '/admin_subpages/editnews', to: 'admins#editnews', via: 'get'
	match '/admin_subpages/deletenews', to: 'news#delete', 	via: 'delete'

	match '/admin_subpages/createuser', to: 'admins#createuser', via: 'get'
	match '/admin_subpages/edituser', to: 'admins#edituser', via: 'get'
	match '/admin_subpages/deleteuser', to: 'admins#dodeleteuser', 	via: 'delete'
	patch '/admin_subpages/edituser' => "admins#doedituser", :as => "admin_edituser"
	post '/admin_subpages/createuser' => "admins#docreateuser", :as => "admin_createuser"

	match '/admin_subpages/createcarouselimage', to: 'admins#createcarouselimage', via: 'get'
	match '/admin_subpages/deletecarouselimage', to: 'admins#dodeletecarouselimage', via: 'delete'
	post '/admin_subpages/createcarouselimage' => "admins#docreatecarouselimage", :as => "admin_createcarouselimage"
	post '/carousel_images/new' => "carousel_images#new", :as => "carousel_new_add"

	match '/admin_subpages/staticpages/createvideo', to: 'adminsstaticpages#createvideo', via: 'get'
	match '/admin_subpages/staticpages/editvideo', to: 'adminsstaticpages#editvideo', via: 'get'
	match '/admin_subpages/staticpages/deletevideo', to: 'adminsstaticpages#dodeletevideo', 	via: 'delete'
	patch '/admin_subpages/staticpages/editvideo' => "adminsstaticpages#doeditvideo", :as => "admin_editvideo"
	post '/admin_subpages/staticpages/createvideo' => "adminsstaticpages#docreatevideo", :as => "admin_createvideo"

	match '/admin_subpages/createsection', to: 'admins#createsection', via: 'get'
	match '/admin_subpages/deletesection', to: 'admins#dodeletesection', 	via: 'delete'
	post '/admin_subpages/createsection' => "admins#docreatesection", :as => "admin_createsection"
	post '/admin_subpages/videos' => "videos#update", :as => "admin_edit_video_description_page"

	post '/admin_subpages/inviteusers' => "admins#inviteuser", :as => "admin_inviteusers"

	post 'help' => "static_pages#send_feedback", :as => "sendfeedback"

	root "static_pages#home"
end

app/controllers/adminsstaticpages_controller.rb
class AdminsstaticpagesController < ApplicationController

	def home
		@homecontent = StaticPage.find_by(title: 'home')
	end

	def updatehome
		homecontent = StaticPage.find_by(title: 'home')
		homecontent.content = params[:static_page][:content].to_s.html_safe

		if homecontent.save(validate: false)
			flash[:form_success] = "Home Content has been updated."
			redirect_to admin_updatehome_path
		else
			flash[:form_errors] = "Failure. Some parameters are invalid: <ul>"
			homecontent.errors.full_messages.each do |error|
				flash[:form_errors] += "<li>" + error + "</li>"
			end
			flash[:form_errors] += "</ul>"
			redirect_to admin_updatehome_path
		end

	end

	def datasheets

	end

	def about

	end

	def presentations_papers

	end

	def videos
		@user = current_user
		@myvideosindex = Settings.find(1).videos_index_description_html
	end

	def createvideo
		@user = current_user

		@createvideo = Video.new
		render 'adminsstaticpages/forms/_video_create'
	end

	def editvideo
		@user = current_user

		@editvideo = Video.find(params[:id])
		render 'adminsstaticpages/forms/_video_edit'
	end

	def docreatevideo
		@user = current_user

		video = Video.new
		video.attributes = video_params

		if video.save(validate: true)
			flash[:form_success] = "Video has been createvideo."
			redirect_to admin_subpages_staticpages_videos_path
		else
			flash[:form_errors] = "Failure. Some parameters are invalid: <ul>"
			video.errors.full_messages.each do |error|
				flash[:form_errors] += "<li>" + error + "</li>"
			end
			flash[:form_errors] += "</ul>"
			redirect_to admin_subpages_staticpages_videos_path
		end
	end

	def doeditvideo
		@user = current_user

		video = Video.find(params[:id])
		video.attributes = video_params

		if video.save(validate: true)
			flash[:form_success] = "Video has been edited."
			redirect_to admin_subpages_staticpages_videos_path
		else
			flash[:form_errors] = "Failure. Some parameters are invalid: <ul>"
			video.errors.full_messages.each do |error|
				flash[:form_errors] += "<li>" + error + "</li>"
			end
			flash[:form_errors] += "</ul>"
			redirect_to admin_subpages_staticpages_videos_path
		end
	end

	def dodeletevideo
		video = Video.find_by_id(params[:id])
		 if video.destroy
		 	flash[:form_success] = "Video successfully deleted"
		 else
		 	flash[:form_errors] = "Video failed to delete."
		 end

		redirect_to admin_subpages_staticpages_videos_path
	end

	def createsection
		@createsection = VideoSection.new

		render 'adminsstaticpages/forms/_section_create'
	end

	def docreatesection
		section  = VideoSection.new
		section.title= params[:video_section][:title]

		if section.save
			flash[:form_success] = "Created a section"
			redirect_to '/admin_subpages/videos'
		else
			flash[:form_errors] = "Failure. Some parameters are invalid: <ul>"
			section.errors.full_messages.each do |error|
				flash[:form_errors] += "<li>" + error + "</li>"
			end
			flash[:form_errors] += "</ul>"
			@createsection = VideoSection.new
			render 'adminsstaticpages/forms/_section_create' 
		end
	end

	def dodeletesection
		section = VideoSection.find_by_id(params[:id])

		if section.destroy
			flash[:form_success] = "Section deleted"
			redirect_to '/admin_subpages/createsection'
		else
			flash[:form_errors] = "Section did not get deleted"
			render 'adminsstaticpages/forms/_section_create'
		end
	end

	private

		def video_params
			params.require(:video).permit(:title, :author, :comments, :video_section_id, :url)
		end
end

app/views/adminsstaticpages/about.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - static pages - about")
	%>

	<%= render 'adminsstaticpages/forms/menu' %>

	ABOUT
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/adminsstaticpages/datasheets.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - static pages - data sheets")
	%>

	<%= render 'adminsstaticpages/forms/menu' %>

	DATASHEETS
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/adminsstaticpages/home.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - static pages - home")
	%>

	<%= render 'adminsstaticpages/forms/menu' %>

		<table class="information_edit_form">
			<%= form_for @homecontent, url: admin_updatehome_path do |f| %>
				<tr>
					<th colspan='2'><h3>Update static home content</h3></th>
				</tr>
				<tr>
					<td colspan='2'><%= f.text_area :content, :class => 'ckeditor' %></td>
				</tr>
				<tr>
					<td colspan='2' class="button"><%= f.submit "Update", class: "btn btn-default btn-lg btn-block"  %> </td>
				</tr>
			<% end %>
		</table>
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/adminsstaticpages/presentations_papers.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - static pages - presentations & papers")
	%>

	<%= render 'adminsstaticpages/forms/menu' %>

	PRESENTATIONS PAPERS
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/adminsstaticpages/videos.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - static pages - videos")
	%>

	<%= render 'adminsstaticpages/forms/menu' %>

<%= render 'adminsstaticpages/forms/video_headers' %>

<%= link_to "Create Video", admin_subpages_staticpages_createvideo_path, class: "btn btn-default btn-lg btn-block" %>

<%=  form_for admin_edit_video_description_page_path do |f| %>
	<table class="information_edit_form">
		<tr>
			<th colspan='2'><h3>Videos static page - Update</h3></th>
		</tr>
		<tr>
			<td class="textfield"><%= f.text_area(:myvideosindex, value: @myvideosindex, :class => 'ckeditor') %></td></td>
		</tr>
		<tr>
			<td colspan='2' class="button"> <%= f.submit "Save changes", class: "btn btn-default btn-lg btn-block" %> </td>
		</tr>
	</table>
<% end %>
<%= render 'admins/admin_subpages/bottomhalf' %>