config/routes.rb
Mccm::Application.routes.draw do
	get "users/new"

	resources :news, only: [:new, :edit, :update, :delete, :show]
	resources :videos, only: [:index, :show,:update, :delete]
	resources :sessions, only: [:new, :create, :destroy]
	resources :settings, only: [:update, :edit]

	resources :carousel_images, only: [:new, :update, :delete, :show]

	resources :users do
		member do
			get :email
			get :files
		end
	end

	resources :news do
		member do
			patch :edit
		end
	end

	match '/presentations',		to: 'static_pages#presentations',	 via: 'get'
	match '/datasheets',		      to: 'static_pages#datasheets',	       via: 'get'	
	match '/results',		      to: 'static_pages#results',	       via: 'get'
	match '/help', 		        to: 'static_pages#help', 	         via: 'get'
	match '/about', 		      to: 'static_pages#about', 	       via: 'get'
	match '/home', 		        to: 'static_pages#home', 	         via: 'get'
	match '/register', 	      to: 'users#new', 			             via: 'get'
	match '/signin',          to: 'sessions#new',                via: 'get'
	match '/signout',         to: 'sessions#destroy',            via: 'delete'
	match '/verify', 		to: 'static_pages#verifyaccount', via: 'get'
	match '/invited', to: 'static_pages#inviteaccount', via: 'get'
	match 'admin_subpages/staticpages', to: 'admins#staticpages', via: 'get'
	match '/admin_subpages/staticpages/home', to: 'adminsstaticpages#home', via: 'get'
	match '/admin_subpages/staticpages/about', to: 'adminsstaticpages#about', via: 'get'
	match '/admin_subpages/staticpages/datasheets', to: 'adminsstaticpages#datasheets', via: 'get'
	match '/admin_subpages/staticpages/presentations_papers', to: 'adminsstaticpages#presentations_papers', via: 'get'
	match '/admin_subpages/staticpages/videos', to: 'adminsstaticpages#videos', via: 'get'
	patch '/admin_subpages/staticpages/home' => "adminsstaticpages#updatehome", :as => "admin_updatehome"

	match '/admin_subpages/', to: 'admins#index',   via: 'get'
	match '/admin_subpages/index', to: 'admins#index', via: 'get'
	match '/admin_subpages/news', to: 'admins#news', via: 'get'
	match '/admin_subpages/settings', to: 'admins#settings', via: 'get'
	match '/admin_subpages/videos', to: 'admins#videos', via: 'get'
	match '/admin_subpages/results', to: 'admins#results', via: 'get'
	match '/admin_subpages/presentations', to: 'admins#presentations', via: 'get'
	match '/admin_subpages/help', to: 'admins#help', via: 'get'
	match '/admin_subpages/about', to: 'admins#about', via: 'get'
	match '/admin_subpages/users', to: 'admins#users', via: 'get'
	match '/admin_subpages/placeholder', to: 'admins#placeholder', via: 'get'
	match '/admin_subpages/carouselimages', to: 'admins#carouselimages', via: 'get'
	match '/admin_subpages/inviteusers', to: 'admins#inviteusers', via: 'get'

	match '/admin_subpages/createnews', to: 'admins#createnews', via: 'get'
	match '/admin_subpages/editnews', to: 'admins#editnews', via: 'get'
	match '/admin_subpages/deletenews', to: 'news#delete', 	via: 'delete'

	match '/admin_subpages/createuser', to: 'admins#createuser', via: 'get'
	match '/admin_subpages/edituser', to: 'admins#edituser', via: 'get'
	match '/admin_subpages/deleteuser', to: 'admins#dodeleteuser', 	via: 'delete'
	patch '/admin_subpages/edituser' => "admins#doedituser", :as => "admin_edituser"
	post '/admin_subpages/createuser' => "admins#docreateuser", :as => "admin_createuser"

	match '/admin_subpages/createcarouselimage', to: 'admins#createcarouselimage', via: 'get'
	match '/admin_subpages/deletecarouselimage', to: 'admins#dodeletecarouselimage', via: 'delete'
	post '/admin_subpages/createcarouselimage' => "admins#docreatecarouselimage", :as => "admin_createcarouselimage"
	post '/carousel_images/new' => "carousel_images#new", :as => "carousel_new_add"

	match '/admin_subpages/staticpages/createvideo', to: 'adminsstaticpages#createvideo', via: 'get'
	match '/admin_subpages/staticpages/editvideo', to: 'adminsstaticpages#editvideo', via: 'get'
	match '/admin_subpages/staticpages/deletevideo', to: 'adminsstaticpages#dodeletevideo', 	via: 'delete'
	patch '/admin_subpages/staticpages/editvideo' => "adminsstaticpages#doeditvideo", :as => "admin_editvideo"
	post '/admin_subpages/staticpages/createvideo' => "adminsstaticpages#docreatevideo", :as => "admin_createvideo"

	match '/admin_subpages/createsection', to: 'admins#createsection', via: 'get'
	match '/admin_subpages/deletesection', to: 'admins#dodeletesection', 	via: 'delete'
	post '/admin_subpages/createsection' => "admins#docreatesection", :as => "admin_createsection"
	post '/admin_subpages/videos' => "videos#update", :as => "admin_edit_video_description_page"

	post '/admin_subpages/inviteusers' => "admins#inviteuser", :as => "admin_inviteusers"

	post 'help' => "static_pages#send_feedback", :as => "sendfeedback"

	root "static_pages#home"
end

app/views/admins/about.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - about")
	%>
	about
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/carouselimages.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - carousel images")
	%>
	<%= render 'admins/admin_subpages/carousel_headers' %>

	<%= link_to "New Image", admin_subpages_createcarouselimage_path, class: "btn btn-default btn-lg btn-block" %>
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/help.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - help")
	%>
	todo: crud on faq<br/>
	todo: crud on static page
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/index.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - Status")
	%>
	this shall be the status and summary of all website activity thus far
	<br/>
	<br/>
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/inviteusers.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - invite users")
	%>
<% if yield_registration_mode == 2 %>
<table class="information_edit_form">
		<%= form_for admin_inviteusers_path do |f| %>
			<tr>
				<th colspan='2'><h3>Invite a User</h3></th>
			</tr>
			<tr>
				<td class="label">E-Mail:</td>
				<td class="textfield"><%= f.text_field :email, :placeholder => 'E-Mail Address',:class => 'register_user_input'  %></td>
			</tr>
			<tr>
				<td colspan='2' class="button"><%= f.submit "Invite", class: "btn btn-default btn-lg btn-block" %></td>
			</tr>
	<% end %>
</table>
<% else %>
	<%= form_errors('Registration mode should be set to "E-Mail Invite Only" for this function to operate.') %>
<% end %>
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/news.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - news")
	%>

	<%= render 'admins/admin_subpages/news_headers' %>

	<%= link_to "Create News", "/admin_subpages/createnews", class: "btn btn-default btn-lg btn-block" %>
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/placeholder.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - placeholder")
	%>
	placeholder
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/results.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - results")
	%>
	results
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/settings.html.erb
<script type="text/javascript">
	$('.ckeditor').ckeditor({
	  // optional config
	});
</script>

<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - settings")
	%>
	<%=  form_for @set do |f| %>
		<table class="information_edit_form">
			<tr>
				<th colspan='2'><h3>Update website settings</h3></th>
			</tr>
			<tr>
				<td class="label">Title:</td>
				<td class="textfield"><%= f.text_field :title, :placeholder => "Title", :class => 'register_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Copyright:</td>
				<td class="textfield"><%= f.text_field :copyright, :placeholder => "Copyright", :class => 'register_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Moto:</td>
				<td class="textfield"><%= f.text_field :moto, :placeholder => "Moto (top right corner)", :class => 'register_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Admin Email: </td>
				<td class="textfield"><%= f.text_field :admin_email, placeholder: "Admin Contact Email", class: 'register_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Developer Email: </td>
				<td class="textfield"><%= f.text_field :developer_email, placeholder: "Developer Email", class: 'register_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Default "FROM" Email: </td>
				<td class="textfield"><%= f.text_field :default_from_email, placeholder: "Default FROM Email", class: 'register_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Server URL: </td>
				<td class="textfield"><%= f.text_field :server_url, placeholder: "Server URL without 'http://'", class: 'register_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Carousel Mode:</td>
				<td class="textfield"><%= f.select :carousel_mode, [['Always ON', 0], ['Always OFF', 1], ['Home page ONLY', 2]], :class => 'reigster_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Registration Mode:</td>
				<td class="textfield"><%= f.select :registration_mode, [['Open registration', 0], ['Email confirmation required', 1], ['Email invite only', 2], ['Admin confirmation required', 2]], :class => 'reigster_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Use FAQ:</td>
				<td class="textfield"><%= f.select :display_faq, [['Yes', 0], ['No', 1]], :class => 'reigster_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Contact Us Mode:</td>
				<td class="textfield"><%= f.select :contactus_mode, [['Everyone', 0], ['Users only', 1]], :class => 'reigster_user_input' %></td>
			</tr>
			<tr>
				<td colspan='2' class="button"> <%= f.submit "Save changes", class: "btn btn-default btn-lg btn-block" %> </td>
			</tr>
		</table>
	<% end %>
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/staticpages.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - static pages")
	%>

	<%= render 'adminsstaticpages/forms/menu' %>

	<%= link_to "Create a Static Page", "/admin_subpages/createstaticpage", class: "btn btn-default btn-lg btn-block" %>
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/users.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - users")
	%>
	<%= render 'admins/admin_subpages/users_headers' %>

	<%= link_to "Create User", admin_subpages_createuser_path, class: "btn btn-default btn-lg btn-block" %>
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/videos.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - videos")
	%>
<%= render 'admins/admin_subpages/video_headers' %>

<%= link_to "Create Video", admin_subpages_createvideo_path, class: "btn btn-default btn-lg btn-block" %>

<%=  form_for admin_edit_video_description_page_path do |f| %>
	<table class="information_edit_form">
		<tr>
			<th colspan='2'><h3>Videos static page - Update</h3></th>
		</tr>
		<tr>
			<td class="textfield"><%= f.text_area(:myvideosindex, value: @myvideosindex, :class => 'ckeditor') %></td></td>
		</tr>
		<tr>
			<td colspan='2' class="button"> <%= f.submit "Save changes", class: "btn btn-default btn-lg btn-block" %> </td>
		</tr>
	</table>
<% end %>
<%= render 'admins/admin_subpages/bottomhalf' %>