config/routes.rb
Mccm::Application.routes.draw do
	get "users/new"

	resources :news, only: [:new, :edit, :update, :delete, :show]
	resources :videos, only: [:index, :show,:update, :delete]
	resources :sessions, only: [:new, :create, :destroy]
	resources :settings, only: [:update, :edit]

	resources :carousel_images, only: [:new, :update, :delete, :show]

	resources :users do
		member do
			get :email
			get :files
		end
	end

	resources :news do
		member do
			patch :edit
		end
	end

	match '/presentations',		to: 'static_pages#presentations',	 via: 'get'
	match '/datasheets',		      to: 'static_pages#datasheets',	       via: 'get'	
	match '/results',		      to: 'static_pages#results',	       via: 'get'
	match '/help', 		        to: 'static_pages#help', 	         via: 'get'
	match '/about', 		      to: 'static_pages#about', 	       via: 'get'
	match '/home', 		        to: 'static_pages#home', 	         via: 'get'
	match '/register', 	      to: 'users#new', 			             via: 'get'
	match '/signin',          to: 'sessions#new',                via: 'get'
	match '/signout',         to: 'sessions#destroy',            via: 'delete'
	match '/verify', 		to: 'static_pages#verifyaccount', via: 'get'
	match '/invited', to: 'static_pages#inviteaccount', via: 'get'
	match 'admin_subpages/staticpages', to: 'admins#staticpages', via: 'get'
	match '/admin_subpages/staticpages/home', to: 'adminsstaticpages#home', via: 'get'
	match '/admin_subpages/staticpages/about', to: 'adminsstaticpages#about', via: 'get'
	match '/admin_subpages/staticpages/datasheets', to: 'adminsstaticpages#datasheets', via: 'get'
	match '/admin_subpages/staticpages/presentations_papers', to: 'adminsstaticpages#presentations_papers', via: 'get'
	match '/admin_subpages/staticpages/videos', to: 'adminsstaticpages#videos', via: 'get'
	patch '/admin_subpages/staticpages/home' => "adminsstaticpages#updatehome", :as => "admin_updatehome"

	match '/admin_subpages/', to: 'admins#index',   via: 'get'
	match '/admin_subpages/index', to: 'admins#index', via: 'get'
	match '/admin_subpages/news', to: 'admins#news', via: 'get'
	match '/admin_subpages/settings', to: 'admins#settings', via: 'get'
	match '/admin_subpages/videos', to: 'admins#videos', via: 'get'
	match '/admin_subpages/results', to: 'admins#results', via: 'get'
	match '/admin_subpages/presentations', to: 'admins#presentations', via: 'get'
	match '/admin_subpages/help', to: 'admins#help', via: 'get'
	match '/admin_subpages/about', to: 'admins#about', via: 'get'
	match '/admin_subpages/users', to: 'admins#users', via: 'get'
	match '/admin_subpages/placeholder', to: 'admins#placeholder', via: 'get'
	match '/admin_subpages/carouselimages', to: 'admins#carouselimages', via: 'get'
	match '/admin_subpages/inviteusers', to: 'admins#inviteusers', via: 'get'

	match '/admin_subpages/createnews', to: 'admins#createnews', via: 'get'
	match '/admin_subpages/editnews', to: 'admins#editnews', via: 'get'
	match '/admin_subpages/deletenews', to: 'news#delete', 	via: 'delete'

	match '/admin_subpages/createuser', to: 'admins#createuser', via: 'get'
	match '/admin_subpages/edituser', to: 'admins#edituser', via: 'get'
	match '/admin_subpages/deleteuser', to: 'admins#dodeleteuser', 	via: 'delete'
	patch '/admin_subpages/edituser' => "admins#doedituser", :as => "admin_edituser"
	post '/admin_subpages/createuser' => "admins#docreateuser", :as => "admin_createuser"

	match '/admin_subpages/createcarouselimage', to: 'admins#createcarouselimage', via: 'get'
	match '/admin_subpages/deletecarouselimage', to: 'admins#dodeletecarouselimage', via: 'delete'
	post '/admin_subpages/createcarouselimage' => "admins#docreatecarouselimage", :as => "admin_createcarouselimage"
	post '/carousel_images/new' => "carousel_images#new", :as => "carousel_new_add"

	match '/admin_subpages/staticpages/createvideo', to: 'adminsstaticpages#createvideo', via: 'get'
	match '/admin_subpages/staticpages/editvideo', to: 'adminsstaticpages#editvideo', via: 'get'
	match '/admin_subpages/staticpages/deletevideo', to: 'adminsstaticpages#dodeletevideo', 	via: 'delete'
	patch '/admin_subpages/staticpages/editvideo' => "adminsstaticpages#doeditvideo", :as => "admin_editvideo"
	post '/admin_subpages/staticpages/createvideo' => "adminsstaticpages#docreatevideo", :as => "admin_createvideo"

	match '/admin_subpages/createsection', to: 'admins#createsection', via: 'get'
	match '/admin_subpages/deletesection', to: 'admins#dodeletesection', 	via: 'delete'
	post '/admin_subpages/createsection' => "admins#docreatesection", :as => "admin_createsection"
	post '/admin_subpages/videos' => "videos#update", :as => "admin_edit_video_description_page"

	post '/admin_subpages/inviteusers' => "admins#inviteuser", :as => "admin_inviteusers"

	post 'help' => "static_pages#send_feedback", :as => "sendfeedback"

	root "static_pages#home"
end

app/views/admins/admin_subpages/_bottomhalf.html.erb
		</div>
	</div>
</div>

app/views/admins/admin_subpages/_carousel_create.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - carousel images - create")
	%>
	<%= render 'admins/admin_subpages/carousel_headers' %>

	<div>
		<%= form_for @carousel, url: carousel_new_add_path do |f| %>
			<%= f.file_field :image %>
			<br/>
			<%= f.hidden_field  :author, value: kirauthor(current_user) %>
			<%= f.submit "Add an image", class: "btn btn-default btn-lg btn-block"  %>
		<% end %>
	</div>	
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/admin_subpages/_carousel_edit.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - carousel images - edit")
	%>
	<%= render 'admins/admin_subpages/carousel_headers' %>

	<div>
		<%= form_for @carousel, url: carousel_new_add_path do |f| %>
			<%= f.file_field :image %>
			<br/>
			<%= f.hidden_field  :author, value: kirauthor(current_user) %>
			<%= f.submit "Edit this image", class: "btn btn-default btn-lg btn-block"  %>
		<% end %>
	</div>	
<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/admin_subpages/_carousel_headers.html.erb
<table class="admin_panel_news_table">
	<tr>
		<th>#</th>
		<th>Preview</th>
		<th>Author</th>
		<th>Created At</th>
		<th>Delete</th>
	</tr>

	<% 
		counter = 0
		@allimages.each do |img|
			counter+=1
	%>
			<tr>
				<td><%= counter %></td>
				<td><%= image_tag img.image.url(:preview) %></td>
				<td><%= img.author %></td>
				<td><%= img.created_at.to_s %></td>
				<td><%= link_to "delete", admin_subpages_deletecarouselimage_path(:id => img.id), method: :delete,
                                  data: { confirm: "You sure?" }%></td>
			</tr>
	<%= will_paginate @allimages %>
	<% end %>
</table>
<br/>

app/views/admins/admin_subpages/_menu.html.erb
<table class="admin_panel_links">
	<tr>
		<td>
			<%= link_to admin_subpages_index_path do %>
				<div <% if controller?("admins") && action?("index") %> id="active" <% end %>> 
					Status
				</div>
			<% end %>
		</td>
		<td>
			<%= link_to admin_subpages_settings_path do %>
				<div <% if controller?("admins") && action?("settings") %> id="active" <% end %>>
					Web Settings
				</div>
			<% end %>
		</td>
		<td>
			<%= link_to admin_subpages_news_path do %>
				<div <% if controller?("admins") && action?("news", "editnews", "createnews") %> id="active" <% end %>> 
					News
				</div>
			<% end %>
		</td>
		<td>
			<%= link_to admin_subpages_users_path do %>
				<div <% if controller?("admins") && action?("users", "createuser", "edituser") %> id="active" <% end %>> 
					Manage Users
				</div>
			<% end %>
		</td>
		<td>
			<%= link_to admin_subpages_inviteusers_path do %>
				<div <% if controller?("admins") && action?("inviteusers") %> id="active" <% end %>> 
					Invite Users
				</div>
			<% end %>
		</td>
		<td>
			<%= link_to admin_subpages_carouselimages_path do %>
				<div <% if controller?("admins") && action?("carouselimages") %> id="active" <% end %>> 
					Carousel Images
				</div>
			<% end %>
		</td>
		<td>
			<%= link_to admin_subpages_staticpages_path do %>
				<div <% if (controller?("admins") && action?("staticpages")) || controller?("adminsstaticpages") %> id="active" <% end %>> 
					Custom Pages
				</div>
			<% end %>
		</td>
	</tr>
</table>

app/views/admins/admin_subpages/_news_create.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - create news")
	%>
<%= render 'admins/admin_subpages/news_headers' %>

<script type="text/javascript">
	$('.ckeditor').ckeditor({
	  // optional config
	});
</script>

<div class="edit_form">
	<table class="information_edit_form">
		<%= form_for @news do |f| %>
			<tr>
				<th colspan='2'><h3>Create News</h3></th>
			</tr>
			<tr>
				<td class="label">Title:</td>
				<td class="textfield"><%= f.text_field :title, :placeholder => "Title", :class => 'register_user_input'  %></td>
			</tr>
			<tr>
				<td colspan='2'><%= f.text_area :content, :class => 'ckeditor' %></td>
			</tr>
			<tr>
				<td colspan='2' class="button"><%= f.submit "Create", class: "btn btn-default btn-lg btn-block" %> </td>
			</tr>
			<%= f.hidden_field :author, :value => (kircapitalize(current_user.first_name)+ " " +kircapitalize(current_user.last_name))%>
		<% end %>
	</table>
</div>

<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/admin_subpages/_news_edit.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - edit news")
	%>

	<%= render 'admins/admin_subpages/news_headers' %>

	<script type="text/javascript">
		$('.ckeditor').ckeditor({
		  // optional config
		});
	</script>

<div class="edit_form">
	<table class="information_edit_form">
		<%= form_for @news, url: edit_news_path(id: @news.id) do |f|%>
			<tr>
				<th colspan='2'><h3>Edit News</h3></th>
			</tr>
			<tr>
				<td class="label">Title:</td>
				<td class="textfield"><%= f.text_field :title, :placeholder => "Title", :class => 'register_user_input'  %></td>
			</tr>
			<tr>
				<td colspan='2'><%= f.text_area :content, :class => 'ckeditor' %></td>
			</tr>
			<tr>
				<td colspan='2' class="button"><%= f.submit "Edit", class: "btn btn-default btn-lg btn-block"  %> </td>
			</tr>
			<%= f.hidden_field :author, :value => (kircapitalize(current_user.first_name)+ " " +kircapitalize(current_user.last_name))%>
		<% end %>
	</table>
</div>

<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/admin_subpages/_news_headers.html.erb
<table class="admin_panel_news_table">
	<tr>
		<th>#</th>
		<th>Title</th>
		<th>Author</th>
		<th>Created At</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>

	<% news = yield_all_news
		counter = 0
		news.each do |n|
			counter+=1
	%>
			<tr>
				<td><%= counter %></td>
				<td><%= n.title %></td>
				<td><%= n.author %></td>
				<td><%= n.created_at %></td>
				<td><%= link_to "edit", admin_subpages_editnews_path(:id => n.id)%></td>

				<td><%= link_to "delete", admin_subpages_deletenews_path(:id => n.id), method: :delete,
                                  data: { confirm: "You sure?" }%></td>
			</tr>
	<% end %>
</table>
<br/>

app/views/admins/admin_subpages/_tophalf.html.erb
<%
provide(:title, "Control panel - " + current_user.first_name + " - Admin Panel ")
%>

<div class="cp_wholecontainer">
	<div class="cp_container_left">
		<%= render 'users/user_subpages/menu' %>
	</div>
	<div class="cp_container_right">
		<%= render 'admins/admin_subpages/menu' %>
		
		<div class="margin">

app/views/admins/admin_subpages/_user_create.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - create user")
	%>
<%= render 'admins/admin_subpages/users_headers' %>

<script type="text/javascript">
	$('.ckeditor').ckeditor({
	  // optional config
	});
</script>

<%= form_alert("Creating users using this form will bypass validation. Meaning you can input invalid data and bad parameters. Be Careful!") %>

<div class="edit_form">
	<table class="information_edit_form">
		<%= form_for @createuser,  url: admin_createuser_path(id: @createuser.id)  do |f| %>
			<tr>
				<th colspan='2'><h3>Create User</h3></th>
			</tr>
			<tr>
				<td class="label">First Name:</td>
				<td class="textfield"><%= f.text_field :first_name, :placeholder => "First Name", :class => 'register_user_input'  %></td>
			</tr>
			<tr>
				<td class="label">Last Name:</td>
				<td class="textfield"><%= f.text_field :last_name, :placeholder => "Last Name", :class => 'register_user_input'  %></td>
			</tr>
			<tr>
				<td class="label">E-Mail:</td>
				<td class="textfield"><%= f.text_field :email, :placeholder => "E-Mail", :class => 'register_user_input'  %></td>
			</tr>
			<tr>
				<td class="label">Admin Level:</td>
				<td class="textfield"><%= f.select :admin_level, [['Admin', 1], ['Staff', 2], ['User', 0]], :class => 'reigster_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Password:</td>
				<td class="textfield"><%= f.password_field :password, :placeholder => "Password", :class => 'register_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Confirm:</td>
				<td class="textfield"><%= f.password_field :password_confirmation, :placeholder => "Confirmation", :class => 'register_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Avatar:</td>
				<td class="textfield"><%= f.file_field :avatar, :class => 'register_user_input' %></td>
			</tr>
			<tr>
				<td colspan='2' class="button"><%= f.submit "Create User", class: "btn btn-default btn-lg btn-block"  %> </td>
			</tr>
		<% end %>
	</table>
</div>

<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/admin_subpages/_user_edit.html.erb
<%= render 'admins/admin_subpages/tophalf' %>
	<%
		provide(:title,  " - edit user")
	%>
<%= render 'admins/admin_subpages/users_headers' %>

<script type="text/javascript">
	$('.ckeditor').ckeditor({
	  // optional config
	});
</script>

<%= form_alert("Editing users using this form will bypass validation. Meaning you can input invalid data and bad parameters. Be Careful!") %>

<div class="edit_form">
	<table class="information_edit_form">
		<%= form_for @edituser, url: admin_edituser_path(id: @edituser.id)  do |f|%>
			<tr>
				<th colspan='2'><h3>Edit User</h3></th>
			</tr>
			<tr>
				<td class="label">First Name:</td>
				<td class="textfield"><%= f.text_field :first_name, :placeholder => "First Name", :class => 'register_user_input'  %></td>
			</tr>
			<tr>
				<td class="label">Last Name:</td>
				<td class="textfield"><%= f.text_field :last_name, :placeholder => "Last Name", :class => 'register_user_input'  %></td>
			</tr>
			<tr>
				<td class="label">E-Mail:</td>
				<td class="textfield"><%= f.text_field :email, :placeholder => "E-Mail", :class => 'register_user_input'  %></td>
			</tr>
			<tr>
				<td class="label">Admin Level:</td>
				<td class="textfield"><%= f.select :admin_level, [['Admin', 1], ['Staff', 2], ['User', 0]], :class => 'reigster_user_input' %></td>
			</tr>
			<tr>
				<td class="label">Avatar:</td>
				<td class="textfield"><%= f.file_field :avatar, :class => 'register_user_input' %></td>
			</tr>
			<tr>
				<td colspan='2' class="button"><%= f.submit "Edit", class: "btn btn-default btn-lg btn-block"  %> </td>
			</tr>
		<% end %>
	</table>
</div>

<%= render 'admins/admin_subpages/bottomhalf' %>

app/views/admins/admin_subpages/_users_headers.html.erb
<table class="admin_panel_news_table">
	<tr>
		<th>#</th>
		<th>Name</th>
		<th>Email</th>
		<th>Created At</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>

	<% 
		counter = 0
		@users.each do |user| 
			counter+=1
	%>
			<tr>
				<td><%= counter %></td>
				<td><%= user.first_name.to_s + " " + user.last_name.to_s %></td>
				<td><%= user.email .to_s %></td>
				<td><%= user.created_at.to_s %></td>
				<td><%= link_to "edit", admin_subpages_edituser_path(:id => user.id)%></td>

				<td><%= link_to "delete", admin_subpages_deleteuser_path(:id => user.id), method: :delete,
                                  data: { confirm: "You sure?" }%></td>
			</tr>
	<% end %>
</table>
<br/>