config/routes.rb
Mccm::Application.routes.draw do
	get "users/new"

	resources :news, only: [:new, :edit, :update, :delete, :show]
	resources :videos, only: [:index, :show,:update, :delete]
	resources :sessions, only: [:new, :create, :destroy]
	resources :settings, only: [:update, :edit]

	resources :carousel_images, only: [:new, :update, :delete, :show]

	resources :users do
		member do
			get :email
			get :files
		end
	end

	resources :news do
		member do
			patch :edit
		end
	end

	match '/presentations',		to: 'static_pages#presentations',	 via: 'get'
	match '/datasheets',		      to: 'static_pages#datasheets',	       via: 'get'	
	match '/results',		      to: 'static_pages#results',	       via: 'get'
	match '/help', 		        to: 'static_pages#help', 	         via: 'get'
	match '/about', 		      to: 'static_pages#about', 	       via: 'get'
	match '/home', 		        to: 'static_pages#home', 	         via: 'get'
	match '/register', 	      to: 'users#new', 			             via: 'get'
	match '/signin',          to: 'sessions#new',                via: 'get'
	match '/signout',         to: 'sessions#destroy',            via: 'delete'
	match '/verify', 		to: 'static_pages#verifyaccount', via: 'get'
	match '/invited', to: 'static_pages#inviteaccount', via: 'get'
	match 'admin_subpages/staticpages', to: 'admins#staticpages', via: 'get'
	match '/admin_subpages/staticpages/home', to: 'adminsstaticpages#home', via: 'get'
	match '/admin_subpages/staticpages/about', to: 'adminsstaticpages#about', via: 'get'
	match '/admin_subpages/staticpages/datasheets', to: 'adminsstaticpages#datasheets', via: 'get'
	match '/admin_subpages/staticpages/presentations_papers', to: 'adminsstaticpages#presentations_papers', via: 'get'
	match '/admin_subpages/staticpages/videos', to: 'adminsstaticpages#videos', via: 'get'
	patch '/admin_subpages/staticpages/home' => "adminsstaticpages#updatehome", :as => "admin_updatehome"

	match '/admin_subpages/', to: 'admins#index',   via: 'get'
	match '/admin_subpages/index', to: 'admins#index', via: 'get'
	match '/admin_subpages/news', to: 'admins#news', via: 'get'
	match '/admin_subpages/settings', to: 'admins#settings', via: 'get'
	match '/admin_subpages/videos', to: 'admins#videos', via: 'get'
	match '/admin_subpages/results', to: 'admins#results', via: 'get'
	match '/admin_subpages/presentations', to: 'admins#presentations', via: 'get'
	match '/admin_subpages/help', to: 'admins#help', via: 'get'
	match '/admin_subpages/about', to: 'admins#about', via: 'get'
	match '/admin_subpages/users', to: 'admins#users', via: 'get'
	match '/admin_subpages/placeholder', to: 'admins#placeholder', via: 'get'
	match '/admin_subpages/carouselimages', to: 'admins#carouselimages', via: 'get'
	match '/admin_subpages/inviteusers', to: 'admins#inviteusers', via: 'get'

	match '/admin_subpages/createnews', to: 'admins#createnews', via: 'get'
	match '/admin_subpages/editnews', to: 'admins#editnews', via: 'get'
	match '/admin_subpages/deletenews', to: 'news#delete', 	via: 'delete'

	match '/admin_subpages/createuser', to: 'admins#createuser', via: 'get'
	match '/admin_subpages/edituser', to: 'admins#edituser', via: 'get'
	match '/admin_subpages/deleteuser', to: 'admins#dodeleteuser', 	via: 'delete'
	patch '/admin_subpages/edituser' => "admins#doedituser", :as => "admin_edituser"
	post '/admin_subpages/createuser' => "admins#docreateuser", :as => "admin_createuser"

	match '/admin_subpages/createcarouselimage', to: 'admins#createcarouselimage', via: 'get'
	match '/admin_subpages/deletecarouselimage', to: 'admins#dodeletecarouselimage', via: 'delete'
	post '/admin_subpages/createcarouselimage' => "admins#docreatecarouselimage", :as => "admin_createcarouselimage"
	post '/carousel_images/new' => "carousel_images#new", :as => "carousel_new_add"

	match '/admin_subpages/staticpages/createvideo', to: 'adminsstaticpages#createvideo', via: 'get'
	match '/admin_subpages/staticpages/editvideo', to: 'adminsstaticpages#editvideo', via: 'get'
	match '/admin_subpages/staticpages/deletevideo', to: 'adminsstaticpages#dodeletevideo', 	via: 'delete'
	patch '/admin_subpages/staticpages/editvideo' => "adminsstaticpages#doeditvideo", :as => "admin_editvideo"
	post '/admin_subpages/staticpages/createvideo' => "adminsstaticpages#docreatevideo", :as => "admin_createvideo"

	match '/admin_subpages/createsection', to: 'admins#createsection', via: 'get'
	match '/admin_subpages/deletesection', to: 'admins#dodeletesection', 	via: 'delete'
	post '/admin_subpages/createsection' => "admins#docreatesection", :as => "admin_createsection"
	post '/admin_subpages/videos' => "videos#update", :as => "admin_edit_video_description_page"

	post '/admin_subpages/inviteusers' => "admins#inviteuser", :as => "admin_inviteusers"

	post 'help' => "static_pages#send_feedback", :as => "sendfeedback"

	root "static_pages#home"
end

app/views/layouts/_carousel.html.erb
<%= javascript_tag do %>
	var carousel_images = new Array();	

	<%
		counter = 0
		yield_all_carousel_images.each do |img|%>

	carousel_images[<%= counter %>] = "<%= img.image.url(:original, timestamp: false) %>";
	<% counter +=1 %>
	<%end%>	
	
	$(window).load(function() {
		$("#photo_container").isc({
			imgArray: carousel_images,
			autoplay: true,
			autoplayTimer: 5000
		});	
	});
<% end %>

<% if yield_carousel_mode == 0 %>
	<div id="photo_container"></div> 
<% elsif yield_carousel_mode == 1 %>
<% elsif yield_carousel_mode == 2 &&  ishomepage? %>
	<div id="photo_container"></div> 
<% end %>

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
      <% if key == :form_errors %>
      		<%= form_errors(value) %>
      <% elsif key == :form_success %>
      		<%= form_success(value) %>
      	<% elsif key == :form_alert %>
      		<%= form_alert(value) %>
      	<% elsif key == :form_warning %>
      		<%= form_warning(value) %>
      	<% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <table id="footer_table">
  	<tr>
  		<td id="first">
  			<%= link_to "Home",   help_path %> | 
  			<%= link_to "Rand",   help_path %>
  		</td>
  		<td id="second"><small><%= yield_copyright %></small></td>
  		<td id="third">
	  		<%= link_to "Help",   help_path %> | 
		    <%= link_to "About", about_path %> | 
		   	<%= link_to "Done",   help_path %>
		</td>
  	</tr>
  </table>
</footer>

app/views/layouts/_header.html.erb
<%
title = yield(:title)
%>

<header class="navbar navbar-static-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      	<table id="KA_header_container">
      		<tr>
      			<td>
      				<table id="KA_header_inner_container">
      					<tr>
      						<td id="header_logo_container"><%= link_to image_tag("logo.png",width: '250'), '/', id: "logo" %></td>
      						<td id="header_content"><%= yield_website_settings_moto.to_s.html_safe %></span></td>
      					</tr>
      				</table>
      			</td>
      		</tr>
      		<tr>
	      		<td id="header_container_menu_links">
	        		<ul class="nav nav-tabs">
			          	<li <%= "class=active" if controller?("static_pages") && action?("home") %>><%= link_to "Home", home_path %></li>
			          	<li <%= "class=active" if controller?("static_pages") && action?("about") %>><%= link_to "About", about_path %></li>
			          	<li <%= "class=active" if controller?("static_pages") && action?("datasheets") %>><%= link_to "Data Sheets", datasheets_path %></li>
			          	<li <%= "class=active" if controller?("static_pages") && action?("presentations") %>><%= link_to "Presentations & Papers", presentations_path %></li>
			          	<li <%= "class=active" if controller?("videos") && action?("show", "index") %>><%= link_to "Videos", videos_path %></li>
			          	<li <%= "class=active" if controller?("users") && action?("new") %>><%= link_to "Register", register_path %></li>
			          	<li <%= "class=active" if controller?("static_pages") && action?("help") %>><%= link_to "Contact Us", help_path %></li>
                  <% if signed_in? %>
			          	  <li <%= "class=active" if (controller?("users")&& action?("show", "edit", "email", "files") || controller?("admins") || controller?("adminsstaticpages"))  %> style="float: right;"><%= link_to "Control Panel", current_user %></li>
                  <% else %>
                    <li <%= "class=active" if title=="Login" %> style="float: right;"><%= link_to "Login", signin_path %></li>
                  <% end %>
	        		</ul>
	        	</td>
	      	</tr>
      	</table>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
	  <%= render 'layouts/shim' %>
</head>

  <body>
  	<div id="wrap">
		<%= render 'layouts/header' %> 
  		<div class="container" id="main_application_container">
        		<%= render 'layouts/carousel' %>
        		<%= render 'layouts/flashes' %>
			<div id="kirkontainer">
				<div id="kirkontainer_header">
					<%= yield(:title) %>
				</div>
				<div id="kirkontainer_padding">
					<%= yield %>
				</div>
			</div>
       			<%= debug(params) if Rails.env.development? %>
		</div>
		<div id="push"></div>
	</div>
  	<div id="footer">
  		<%= render 'layouts/footer' %>
	</div>
  </body>
</html>









<!-- sample of a twitter bootstrap dropdown 
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>
-->